openapi: 3.0.0
info:
  title: org
  version: '1.0'
  description: 'config store API'
servers:
  - url: 'http://localhost:3000'
paths:
  '/org/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      description: 'get'
      summary: get single org info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Org.v1.yaml
      operationId: get-org-id
components:
  schemas: {}
tags:
  - name: org
  - name: user
  - name: product
